add: local initialisation logic
nightwatchjs/nightwatch-plugin-browserstack pull request #1
Opened 2022-11-24 05:42 UTC by 07souravkunda

2022-12-26 13:16 UTC, karanshah-browserstack requested changes

2022-12-26 13:16 UTC, karanshah-browserstack commented on nightwatch/globals.js
> +    console.log(settings.hello, 'hello')
Remove console log

2022-12-26 13:16 UTC, karanshah-browserstack commented on nightwatch/globals.js
> +    console.log('Stopping local');
Remove console log or print meaningful message

2022-12-26 13:16 UTC, karanshah-browserstack commented on nightwatch/globals.js
> +    console.log('Stopping local');
Stopping BrowserStack Local ...

2022-12-26 13:16 UTC, karanshah-browserstack commented on src/local-tunnel.js
> +      this._localStarted && await util.promisify(this._localTunnel.stop.bind(this._localTunnel))();
Add handling for abrupt closes

2022-12-26 13:16 UTC, karanshah-browserstack commented on src/utils/helper.js
> +  if (this.isObject(settings.desiredCapabilities)) {
Fetching key from env vars? Or this would be set inside the options beforehand?

2022-12-27 05:37 UTC, 07souravkunda commented on src/utils/helper.js
> +  if (this.isObject(settings.desiredCapabilities)) {
this would be set inside options by nightwatch

2022-12-29 13:41 UTC, karanshah-browserstack approved these changes
LGTM

2023-01-03 09:48 UTC, swrdfish requested changes

2023-01-03 09:48 UTC, swrdfish commented on nightwatch/globals.js
> +    process.env.BROWSERSTACK_LOCAL_ENABLED == "true" &&
These lines are not readable.

2023-01-03 09:48 UTC, swrdfish commented on nightwatch/globals.js
> +    if (localTunnel._localStarted) {
why do we need `_localStarted` ? Can't we use simple try catch?

2023-01-03 09:48 UTC, swrdfish commented on src/local-tunnel.js
> +      this._localTunnel = new BStackLocal();
Missing curly braces around if statement

2023-01-03 13:28 UTC, 07souravkunda commented on nightwatch/globals.js
> +    if (localTunnel._localStarted) {
Inside `start` method checking for accessKey available and keeping `_localStarted`, which is used at `stop`

2023-01-03 14:00 UTC, karanshah-browserstack approved these changes

2023-01-05 08:01 UTC, swrdfish commented on nightwatch/globals.js
> +    if (localTunnel._localStarted) {
why not error out directly if `localTunnel.start` fails?

2023-01-05 10:02 UTC, karanshah-browserstack requested changes

2023-01-05 11:03 UTC, karanshah-browserstack approved these changes

2023-01-09 12:35 UTC, swrdfish approved these changes
LGTM

2023-01-09 12:57 UTC, beatfactor requested changes
please add:
- .gitignore as in the main nightwatch repo
- eslint task (use the .eslintrc file from the nightwatch repo)
- unit tests
- github actions build

2023-01-13 17:23 UTC, merged