chore: Added support for parallel run in nightwatch cucumber
nightwatchjs/nightwatch-plugin-browserstack pull request #14
Opened 2023-07-12 08:36 UTC by sauravdas1997

2023-07-21 12:00 UTC, sriteja777 requested changes

2023-07-21 12:00 UTC, sriteja777 commented on src/utils/helper.js
> +exports.getUniqueIdentifierForCucumber = (pickle) => {
Are we using this function?

2023-07-21 16:52 UTC, sauravdas1997 commented on nightwatch/globals.js
> +};
done

2023-07-21 16:53 UTC, sauravdas1997 commented on src/utils/constants.js
> +exports.PID_MAPPING_REGEX = /^TEST-OBSERVABILITY-PID-TESTCASE-MAPPING-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;
done

2023-07-21 16:54 UTC, sauravdas1997 commented on src/utils/helper.js
> +exports.getUniqueIdentifierForCucumber = (pickle) => {
removed

2023-07-21 16:56 UTC, sauravdas1997 commented on src/utils/logPatcher.js
> +    ipc.connectTo(IPC_SERVER_NAME, () => {
added

2023-07-21 16:58 UTC, sauravdas1997 commented on src/testObservability.js
> +        if ((sessionCapabilities) && (args.envelope.testCaseStartedId === currentSessionCapabilities.testCaseStartedId)) {
added

2023-07-21 17:07 UTC, sauravdas1997 commented on nightwatch/globals.js
> +        _tests['uniqueId'] = testCaseId;
done

2023-07-21 17:10 UTC, sauravdas1997 commented on nightwatch/globals.js
> +      });
added

2023-07-21 17:23 UTC, sauravdas1997 commented on nightwatch/globals.js
> +        settings.test_runner.options['require'] = 'node_modules/@nightwatch/browserstack/nightwatch/observabilityLogPatcherHook.js';
done

2023-07-22 02:25 UTC, sauravdas1997 commented on nightwatch/globals.js
> +        startIPCServer();
updated

2023-07-22 02:45 UTC, sauravdas1997 commented on package.json
> +    "@cucumber/cucumber": "^8.2.1"
done

2023-07-22 16:17 UTC, sauravdas1997 commented on nightwatch/observabilityLogPatcherHook.js
> +const {Before} = require('@cucumber/cucumber');
done

2023-07-22 18:06 UTC, sauravdas1997 commented on nightwatch/globals.js
> +          browser.execute(`browserstack_executor: {"action": "annotate", "arguments": {"type":"Annotation","data":"ObservabilitySync:${Date.now()}","level": "debug"}}`);
Currently no way to map the hostname of session to a certain test id. Nightwatch isn't sending `testCaseStartedId` in `args.envelope`. Any exception occurred will get handled here.

2023-07-24 10:30 UTC, sriteja777 commented on src/testObservability.js
> +          Logger.error('Failed to upload integrations data');
This log will get shown to user right? Can we instead add a debug log that logs only when debug mode is enabled.

2023-07-24 17:52 UTC, harshit-bs commented on nightwatch/globals.js
> +};
The function looks good overall, but we could take advantage of optional chaining to make it more concise and elegant.

```suggestion
const getUUIDFromPID = (pid) => {
  const testCaseStartedId = _testCasesData[pid];
  const testCaseId = _testCasesData[testCaseStartedId]?.testCaseId;
  return _tests[testCaseId]?.uuid;
};
```

2023-07-24 17:52 UTC, harshit-bs commented on src/utils/logPatcher.js
> +      ipc.config.silent = true;
If possible, can we set default IPC config in a single location, enabling us to utilize it across multiple instances.

2023-07-24 17:52 UTC, harshit-bs commented on src/utils/helper.js
> +  }
```suggestion
  if (!(scenario.astNodeIds?.length > 1)) {
    return;
  }
```

2023-10-18 12:12 UTC, 07souravkunda requested changes

2023-10-18 12:12 UTC, 07souravkunda commented on nightwatch/globals.js
> +      super.parseWorkerMessage(...args);
return  super.parseWorkerMessage(...args);

2023-10-18 12:12 UTC, 07souravkunda commented on nightwatch/globals.js
> +      workerList = this.workers;
startworker runs once?

2023-10-18 12:12 UTC, 07souravkunda commented on nightwatch/globals.js
>        if (helper.isTestObservabilitySession()) {
please add try..catch for observability stuff.

2023-10-18 12:12 UTC, 07souravkunda commented on src/utils/logPatcher.js
> +const eve = require('events');
move package imports to top

2023-10-18 12:12 UTC, 07souravkunda commented on src/utils/logPatcher.js
> +const testObservability = new TestObservability();
move var declarations after imports.

2023-10-18 12:12 UTC, 07souravkunda commented on nightwatch/globals.js
> +const {consoleHolder} = require('../src/utils/constants');
move file imports to top

2023-10-19 03:47 UTC, 07souravkunda commented on nightwatch/globals.js
> +      super.parseWorkerMessage(...args);
args[1]?.eventType

2023-10-19 03:49 UTC, 07souravkunda commented
Fix unit tests

2023-10-27 10:01 UTC, sauravdas1997 commented on nightwatch/globals.js
> +      workerList = this.workers;
no loss in workers

2023-10-27 10:16 UTC, sauravdas1997 commented on nightwatch/globals.js
> +const {consoleHolder} = require('../src/utils/constants');
done

2023-10-27 10:16 UTC, sauravdas1997 commented on nightwatch/globals.js
>        if (helper.isTestObservabilitySession()) {
done

2023-10-27 10:18 UTC, sauravdas1997 commented on nightwatch/globals.js
> +  const Coordinator = helper.requireModule('@cucumber/cucumber/lib/runtime/parallel/coordinator.js');
this method is called only for cucumber, so for safety wrapping a trycatch around it

2023-10-31 06:49 UTC, 07souravkunda approved these changes

2023-10-31 10:35 UTC, gravityvi approved these changes

2023-11-01 07:13 UTC, merged