Add support for accessibility for nightwatch
nightwatchjs/nightwatch-plugin-browserstack pull request #17
Opened 2023-09-05 04:12 UTC by karanshah-browserstack

2023-09-06 09:01 UTC, rev-doshi commented on src/accessibilityAutomation.js
> +            // pageOpen = url.protocol === 'http:' || url.protocol === 'https:';
Why is this commented out? Its part of the logic for pageOpen AFAIR

2023-09-06 09:08 UTC, rev-doshi commented on src/accessibilityAutomation.js
> +        settings: this.filterAccessibilityOptions(accessibilityOptions),
Here we can send the accessibilityOptions itself, don't need the filtered Options

2023-09-06 09:10 UTC, karanshah-browserstack commented on src/accessibilityAutomation.js
> +            // pageOpen = url.protocol === 'http:' || url.protocol === 'https:';
Done

2023-09-07 06:04 UTC, rev-doshi approved these changes

2023-09-07 07:54 UTC, 07souravkunda requested changes

2023-09-07 07:54 UTC, 07souravkunda commented on nightwatch/globals.js
> +    try{
lint: space

2023-09-07 07:54 UTC, 07souravkunda commented on src/accessibilityAutomation.js
> +    if(settings && settings.webdriver && settings.webdriver.host && settings.webdriver.host.indexOf('browserstack') == -1){
create key extractor utility

2023-09-07 07:54 UTC, 07souravkunda commented on src/accessibilityAutomation.js
> +    if(settings && settings.webdriver && settings.webdriver.host && settings.webdriver.host.indexOf('browserstack') == -1){
===

2023-09-07 07:54 UTC, 07souravkunda commented on src/accessibilityAutomation.js
> +
Initialise all class methods in constructor

2023-09-07 07:54 UTC, 07souravkunda commented on src/accessibilityAutomation.js
> +          process.env.BROWSERSTACK_ACCESSIBILITY = 'false';
don't set env vars inside this class, set them as class properties. Set all envs in globals.js|before at one place

2023-09-07 07:54 UTC, 07souravkunda commented on src/accessibilityAutomation.js
> +      typeof process.env.BS_A11Y_JWT !== 'string'
use class property

2023-09-07 07:54 UTC, 07souravkunda commented on src/accessibilityAutomation.js
> +    if (process.env.BROWSERSTACK_ACCESSIBILITY_OPTIONS == null) {
===

2023-09-07 12:38 UTC, 07souravkunda requested changes

2023-09-07 12:38 UTC, 07souravkunda commented on src/accessibilityAutomation.js
> +      return !excluded && included;
if test is not included or excluded it will return false?

2023-09-08 07:24 UTC, 07souravkunda approved these changes

2023-09-27 06:05 UTC, 07souravkunda requested changes

2023-09-27 06:05 UTC, 07souravkunda commented on nightwatch/globals.js
> +    // await accessibilityAutomation.beforeEachExecution(browser);
remove comments

2023-09-27 06:05 UTC, 07souravkunda commented on nightwatch/globals.js
> +    // await accessibilityAutomation.afterEachExecution(browser);
comments

2023-09-27 16:28 UTC, AutomatedTester commented
Before we can merge this we need to have a green ci. can someone sort that?

2023-09-28 08:33 UTC, AutomatedTester commented
@karanshah-browserstack @07souravkunda can someone look at the CI failures?

2023-09-28 09:23 UTC, karanshah-browserstack commented
@AutomatedTester Checking

2023-09-28 09:26 UTC, karanshah-browserstack commented
@AutomatedTester Fixed this.

2023-09-28 09:26 UTC, karanshah-browserstack commented
RUN_TESTS

2023-09-28 10:09 UTC, kamal-kaur04 approved these changes

2023-09-28 12:32 UTC, 07souravkunda approved these changes

2023-10-02 09:29 UTC, merged