fix: Fix test steps when tests are running in parallel
nightwatchjs/nightwatch-plugin-browserstack pull request #23
Opened 2023-12-22 12:50 UTC by sauravdas1997

2024-02-12 05:06 UTC, 07souravkunda requested changes

2024-02-12 05:40 UTC, sauravdas1997 commented on src/utils/helper.js
> +    const sessionDetails = JSON.parse(data.POST_SESSION_EVENT);
Its implicitly getting handled where its invoked. Also, we want to do a crash report on failure, but invoking the CrashReporter will create cyclic dependency

2024-02-13 05:19 UTC, 07souravkunda approved these changes

2024-02-13 05:20 UTC, 07souravkunda requested changes

2024-02-13 05:20 UTC, 07souravkunda commented on src/utils/helper.js
> +  if (this.isUndefined(browser)) {
!this.isUndefined

2024-02-13 05:22 UTC, 07souravkunda approved these changes

2024-02-16 10:36 UTC, AutomatedTester commented on src/utils/helper.js
> +exports.deepClone = (obj) => {
Where is this used? Why can't we use [`structuredClone`](https://developer.mozilla.org/en-US/docs/Web/API/structuredClone) here instead of building our own function?

2024-02-20 12:44 UTC, karanshah-browserstack commented on src/utils/helper.js
> +exports.deepClone = (obj) => {
@AutomatedTester Afaik, structuredClone is introduced in node v17 and above, and since we have minimum required version as v16 in nightwatch, this method is been created to support all the versions.

2024-02-27 11:17 UTC, merged