Support takeElementScreenshot for o11y
nightwatchjs/nightwatch-plugin-browserstack pull request #34
Opened 2024-09-06 09:04 UTC by samarsault

2024-09-06 10:27 UTC, sauravdas1997 commented
This feature is not enabled by default, we have to add the flag in nightwatch_conf as well

2024-09-06 10:27 UTC, sauravdas1997 requested changes

2024-09-06 10:27 UTC, sauravdas1997 commented on src/testObservability.js
> +        } else if (/^.*(takeElementScreenshot)$/.test(command.name) && command.result && command.result.valuePath) {
`.contains` instead if regex ?

2024-09-06 10:27 UTC, sauravdas1997 commented on src/testObservability.js
> +        } else if (/^.*(takeElementScreenshot)$/.test(command.name) && command.result && command.result.valuePath) {
If the bytesize of <500 then it will be value and not valuePath

2024-09-06 10:27 UTC, sauravdas1997 commented on src/testObservability.js
> +        } else if (/^.*(takeElementScreenshot)$/.test(command.name) && command.result && command.result.valuePath) {
optional chaining ? `command?.result?.valuePath`

2024-09-06 12:44 UTC, samarsault commented on src/testObservability.js
> +        } else if (/^.*(takeElementScreenshot)$/.test(command.name) && command.result && command.result.valuePath) {
Won't work in node 12 and NW supports 12.0+

2024-09-06 12:47 UTC, samarsault commented on src/testObservability.js
> +        } else if (/^.*(takeElementScreenshot)$/.test(command.name) && command.result && command.result.valuePath) {
regex is more accurate here and performance difference is minimal

2024-09-06 13:05 UTC, samarsault commented on src/testObservability.js
> +        } else if (/^.*(takeElementScreenshot)$/.test(command.name) && command.result && command.result.valuePath) {
addressed

2024-09-09 05:52 UTC, 07souravkunda requested changes

2024-09-09 05:52 UTC, 07souravkunda commented on src/testObservability.js
> +              await this.createScreenshotLogEvent(testUuid, screenshot, command.startTime);
add graceful error handling

2024-09-09 05:52 UTC, 07souravkunda commented on src/testObservability.js
> +        } else if (/^.*(takeElementScreenshot)$/.test(command.name) && command.result) {
add this regex to constants.
Add a comment why doing this

2024-09-09 05:53 UTC, 07souravkunda requested changes

2024-09-09 05:53 UTC, 07souravkunda commented on src/testObservability.js
> +          if (command.result.value) {
Use nestedKey if you are unsure about whether the `result` exists.

2024-09-09 05:55 UTC, sauravdas1997 commented on src/testObservability.js
> +          if (command.result.value) {
use optional params

2024-09-09 05:58 UTC, sauravdas1997 commented
Nightwatch themselves uses optional chaining, so IMO should be okay to use that

2024-09-09 12:57 UTC, samarsault commented
We dont need optional chaining since we have to check the if path

2024-09-09 12:57 UTC, samarsault commented on src/testObservability.js
> +          if (command.result.value) {
We have a check earlier

2024-09-09 13:01 UTC, samarsault commented on src/testObservability.js
> +        } else if (/^.*(takeElementScreenshot)$/.test(command.name) && command.result) {
done

2024-09-09 13:01 UTC, samarsault commented on src/testObservability.js
> +              await this.createScreenshotLogEvent(testUuid, screenshot, command.startTime);
done

2024-09-10 06:31 UTC, 07souravkunda approved these changes

2024-09-10 09:02 UTC, sauravdas1997 approved these changes

2024-09-12 07:25 UTC, sauravdas1997 approved these changes

2024-09-17 21:26 UTC, merged