Ensuring screenshot reporting on observability + spell check
nightwatchjs/nightwatch-plugin-browserstack pull request #35
Opened 2024-10-03 09:32 UTC by rev-doshi

2024-10-03 11:13 UTC, sauravdas1997 approved these changes

2024-10-03 11:13 UTC, 07souravkunda requested changes

2024-10-03 11:13 UTC, 07souravkunda commented on nightwatch/globals.js
> +        }
```suggestion
settings.reporter_options = {
  save_command_result_value: true,
  ...(settings.reporter_options || {})
};
```

2024-10-03 11:13 UTC, 07souravkunda commented on nightwatch/globals.js
> +        }
Also add a code comment why doing this

2024-10-03 12:26 UTC, 07souravkunda approved these changes

2024-10-08 10:06 UTC, 07souravkunda approved these changes

2024-10-09 10:44 UTC, sauravdas1997 approved these changes

2024-10-09 12:46 UTC, 07souravkunda approved these changes

2024-10-10 08:38 UTC, AutomatedTester approved these changes

2024-10-10 08:39 UTC, merged