added productMap and buildUuid instrumentation
nightwatchjs/nightwatch-plugin-browserstack pull request #37
Opened 2024-11-26 06:29 UTC by dhavalshah24s

2024-11-26 19:53 UTC, karanshah-browserstack commented on nightwatch/globals.js
> +const addProductMapAndbuildUuidCapability = (settings) => {
Add inside try catch block, don't want session to be failing for any unknown exceptions inside our functions.

2024-11-27 09:00 UTC, karanshah-browserstack approved these changes

2024-11-28 06:39 UTC, amaanbs requested changes

2024-11-28 06:39 UTC, amaanbs commented on src/testObservability.js
> +    if (this._settings.test_observability && this._settings.test_observability.enabled !== undefined) {
This won't work if test_observability is set to false. We'll still end up setting the environment variable to true.

2024-11-28 06:39 UTC, amaanbs commented on nightwatch/globals.js
> +    if (!settings?.desiredCapabilities?.['bstack:options']) {
Are we not handling non w3c mode?

2024-11-28 06:39 UTC, amaanbs commented on nightwatch/globals.js
> +      turboscale: false,
We need to track for turboscale as well.
https://github.com/search?q=repo%3Anightwatchjs%2Fnightwatch-plugin-browserstack%20turboscale&type=code

2024-11-28 08:07 UTC, amaanbs requested changes

2024-11-28 08:07 UTC, amaanbs commented on nightwatch/globals.js
> +      automate: helper.getObservabilityLinkedProductName() === 'automate',
Redundant method calls. Refactor.

2024-11-28 08:07 UTC, amaanbs commented on nightwatch/globals.js
> +      settings.desiredCapabilities['buildProductMap'] = buildProductMap;
Does this need a prefix of `browserstack.` ? Is this reflected on the dashboard correctly?

2024-12-09 13:41 UTC, karanshah-browserstack approved these changes

2024-12-16 05:48 UTC, 07souravkunda approved these changes

2024-12-16 08:36 UTC, garg3133 approved these changes

2024-12-16 08:36 UTC, merged