added build start event
nightwatchjs/nightwatch-plugin-browserstack pull request #5
Opened 2023-03-29 12:01 UTC by grkpranaykumar

2023-03-30 06:59 UTC, beatfactor commented on nightwatch/globals.js
> +  reporter: function(results, done) {
not used.

2023-03-30 20:01 UTC, swrdfish commented on src/utils/helper.js
> +    console.log('Unable to find a Git directory');
all console logs should have a prefix to make it clear where the log is coming from, like `nightwatch-browserstack-plugin:`

2023-03-30 20:05 UTC, swrdfish commented on nightwatch/globals.js
> +    if (testObservability._user && testObservability._key) {
if not configure properly should it not throw an error? Also, should enabling testObservability itself not be configurable ? I mean people might want to use localTunnel without using TO, can the not?

2023-03-30 20:24 UTC, swrdfish commented on src/utils/helper.js
> +    if (!fs.existsSync(global_path)) {
No sure if looking for nightwatch in the global path is a good idea. 

@gravityvi thoughts?

2023-03-30 20:26 UTC, swrdfish commented on src/utils/helper.js
> +exports.nodeRequest = (type, url, data, config) => {
`makeRequest` would be a more meaningful name.

2023-03-30 20:28 UTC, swrdfish commented on src/utils/requestQueueHandler.js
> +// const { batchAndPostEvents } = require('./helper');
remove unnecessary comment

2023-03-30 20:28 UTC, swrdfish commented on src/utils/requestQueueHandler.js
> +const { BATCH_SIZE, BATCH_INTERVAL } = require('./constants');
`BATCH_INTERVAL` is unused.

2023-04-12 12:20 UTC, grkpranaykumar commented on nightwatch/globals.js
> +  reporter: function(results, done) {
used for processing reporter object

2023-04-12 12:22 UTC, grkpranaykumar commented on nightwatch/globals.js
> +    if (testObservability._user && testObservability._key) {
yes it is configured now

2023-04-12 12:23 UTC, grkpranaykumar commented on src/utils/helper.js
> +exports.nodeRequest = (type, url, data, config) => {
done

2023-04-12 12:23 UTC, grkpranaykumar commented on src/utils/requestQueueHandler.js
> +// const { batchAndPostEvents } = require('./helper');
done

2023-04-18 18:06 UTC, swrdfish requested changes

2023-04-18 18:06 UTC, swrdfish commented on nightwatch/globals.js
> +        console.log(`nightwatch-browserstack-plugin: Something went wrong in processing report file for test observability - ${error}`);
create a helper function for logs.

2023-04-18 18:06 UTC, swrdfish commented on src/testObservability.js
> +    if (process.argv.includes('--disable-test-observability')) {
should also add a enabled flag in the settings object `testObservabilityOptions`
Also rename `testObservabilityOptions` to `test_observability`

2023-04-20 07:12 UTC, grkpranaykumar commented on src/testObservability.js
> +    if (process.argv.includes('--disable-test-observability')) {
We are following the same naming convention in all SDK's for test observability.

2023-04-20 08:46 UTC, sriteja777 commented on src/utils/helper.js
> +          if (typeof(body) !== 'object') {body = JSON.parse(body)}
Can we do a string check instead?

2023-04-20 08:46 UTC, sriteja777 commented on src/utils/helper.js
> +  if (process.env.BS_TESTOPS_JWT !== 'null') {
When will this be a case?

2023-04-20 08:46 UTC, sriteja777 commented on src/utils/helper.js
> +    if (process.env.BS_TESTOPS_JWT === 'null') {
Are you sure it will be a string null?

2023-04-20 08:46 UTC, sriteja777 commented on src/testObservability.js
> +        message: error.message || error.response ? `${error.response.status}:${error.response.statusText}` : error
If `error.response` is null or undefined, won't this raise an error?

2023-04-20 08:46 UTC, sriteja777 commented on src/testObservability.js
> +      ],
Does this include all hierarchy info?

2023-04-20 08:46 UTC, sriteja777 commented on src/testObservability.js
> +      testData.result = eventData.status === 'pass' ? 'passed' : 'failed';
Won't we be having skipped test as result?

2023-04-21 17:51 UTC, swrdfish commented on src/testObservability.js
> +    if (process.argv.includes('--disable-test-observability')) {
But this is a nightwatch plugin, this configuration will be inside nightwatch. So it should follow nightwatch's coding style. Users trying to add TO will be a nightwatch users, so they will be familiar with nightwatch config.

2023-04-25 05:37 UTC, grkpranaykumar commented on src/testObservability.js
> +      ],
nightwatch has only 1 describe block per test file and it will be read in the name feild

2023-04-25 05:38 UTC, grkpranaykumar commented on src/utils/helper.js
> +    if (process.env.BS_TESTOPS_JWT === 'null') {
environment vars are read as strings only. it is verified

2023-04-25 05:38 UTC, grkpranaykumar commented on src/utils/helper.js
> +          if (typeof(body) !== 'object') {body = JSON.parse(body)}
done

2023-04-25 05:39 UTC, grkpranaykumar commented on src/utils/helper.js
> +  return process.env.BROWSERSTACK_TEST_OBSERVABILITY === 'true';
environment vars are read as strings only. it is verified

2023-05-03 14:34 UTC, gravityvi requested changes
There are circular dependencies in code. Can we fix those?

2023-05-03 14:34 UTC, gravityvi commented on src/utils/requestQueueHandler.js
> +      await helper.batchAndPostEvents(this.eventUrl, 'Shutdown-Queue', data);
Circular dependency. `helper` module is using requestQueueHandler module as well.

2023-05-09 14:01 UTC, swrdfish commented on src/testObservability.js
> +        message: error.message || error.response ? `${error.response.status}:${error.response.statusText}` : error
Yes it can cause an error, @grkpranaykumar please refactor this.

2023-05-09 14:02 UTC, swrdfish commented on src/testObservability.js
> +            await this.sendTestRunEvent(eventData, testFileReport, 'HookRunFinished', globalBeforeEachHookId, 'GLOBAL_BEFORE_EACH', sectionName);
this section is repeated again and again, extract is out into a function

2023-05-09 14:04 UTC, swrdfish commented on nightwatch/globals.js
> +          console.log(`\nVisit https://observability.browserstack.com/builds/${process.env.BS_TESTOPS_BUILD_HASHED_ID} to view build report, insights, and many more debugging information all at one p
use `Logger` here

2023-05-09 14:06 UTC, swrdfish commented on src/utils/helper.js
> +  fs.writeFileSync(RERUN_FILE, JSON.stringify(data), (error) => {
use `fs.promise` and make it async

2023-05-09 14:07 UTC, swrdfish commented on src/utils/helper.js
> +    fs.unlinkSync(path.resolve(RERUN_FILE));
use `fs.promise`

2023-05-09 14:15 UTC, swrdfish commented on src/utils/helper.js
> +    fs.statSync(filePath + '/.git/config');
use `fs.promise`

2023-05-09 14:17 UTC, swrdfish commented on src/utils/helper.js
> +    exports.requestQueueHandler.start();
This is does not make sense.

requestQueueHandler seems to be a singleton, this state management should be in `requestQueueHandler.js` itself.

2023-05-09 14:20 UTC, swrdfish commented on src/utils/helper.js
> +  if (env.CI === 'true' && env.CIRCLECI === 'true') {
can be ignored for now

2023-05-09 14:21 UTC, swrdfish commented on src/testObservability.js
> +      }
can be ignored for now

2023-05-09 14:23 UTC, swrdfish commented on src/utils/requestQueueHandler.js
> +      await helper.batchAndPostEvents(this.eventUrl, 'Shutdown-Queue', data);
yes this needs fixing, making `requestQueueHandler` a singleton will solve this.

2023-05-10 12:23 UTC, sriteja777 approved these changes

2023-05-10 12:23 UTC, sriteja777 approved these changes

2023-05-18 06:03 UTC, swrdfish requested changes

2023-05-18 06:03 UTC, swrdfish commented on src/utils/helper.js
> +  if (process.env.BS_TESTOPS_JWT !== 'null') {
What happens if `process.env.BS_TESTOPS_JWT` is `undefined`?

2023-05-22 07:47 UTC, grkpranaykumar commented on nightwatch/globals.js
> +            promises.push(testObservability.processTestReportFile(JSON.parse(JSON.stringify(modulesWithEnv[testSetting][testFile]))));
Deep copy is necessary because the git modules are changing the values in the object while parsing.

2023-05-22 13:24 UTC, amaanbs approved these changes

2023-05-23 06:59 UTC, sriteja777 approved these changes

2023-05-23 07:28 UTC, grkpranaykumar commented on src/utils/helper.js
> +    } = requestQueueHandler.add(eventData);
@swrdfish these are just the method calls, which can be called anywhere in the code. Can you suggest how can this be moved inside the class itself.

2023-05-23 09:42 UTC, swrdfish commented on src/utils/helper.js
> +    } = requestQueueHandler.add(eventData);
The entire `uploadEventData` should be moved to requestQueueHandler.

2023-05-23 11:57 UTC, vaibhavsingh97 commented on nightwatch/globals.js
> +  },
I think this whole code can be refactored like this


```javascript
reporter: async function(results, done) {
  if (!helper.isTestObservabilitySession()) {
    done(results);
    return;
  }

  try {
    const modulesWithEnv = results['modulesWithEnv'];
    const promises = [];

    for (const testSetting in modulesWithEnv) {
      for (const testFile in modulesWithEnv[testSetting]) {
      const completedSections = modulesWithEnv[testSetting][testFile].completed;

        for (const completedSection in completedSections) {
          if (completedSections[completedSection]) {
            delete completedSections[completedSection].steps;
            delete completedSections[completedSection].testcases;
          }
        }

        // Maybe create a helper method to do `.parse` and `.stringify`
        promises.push(testObservability.processTestReportFile(JSON.parse(JSON.stringify(modulesWithEnv[testSetting][testFile]))));
      }
    }

    await Promise.all(promises);
    done();
  } catch (error) {
    Logger.error(`Something went wrong in processing report file for test observability - ${error.message} with stacktrace ${error.stack}`);
    CrashReporter.uploadCrashReport(error.message, error.stack);
  }
}
```

2023-05-23 12:11 UTC, vaibhavsingh97 commented on src/testObservability.js
> +        throw ({message: response.data.error});
```suggestion
        throw {message: response.data.error};
```

2023-05-23 12:23 UTC, vaibhavsingh97 commented on src/testObservability.js
> +            if (eventData.retryTestData && eventData.retryTestData.length>0) {
```suggestion
            if (eventData.retryTestData?.length) {
```

2023-05-23 12:25 UTC, vaibhavsingh97 commented on src/testObservability.js
> +    const errorData = eventData.commands.find(command => command.result && command.result.stack);
```suggestion
    const errorData = eventData.commands.find(command => command.result?.stack);
```

2023-05-24 06:44 UTC, swrdfish approved these changes

2023-05-24 08:36 UTC, vaibhavsingh97 commented on src/utils/requestHelper.js
> +};
nitpick: I had suggested small refactor

```suggestion
exports.makeRequest = (type, url, data, config) => {
   const isHttps = API_URL.includes('https');
  
   if (url === SCREENSHOT_EVENT_URL) {
      agent = isHttps ? httpsScreenshotsKeepAliveAgent : httpScreenshotsKeepAliveAgent;
   } else {
      agent = isHttps ? httpsKeepAliveAgent : httpKeepAliveAgent;
   }
   
   const options = {
     ...config,
     method: type,
     url: `${API_URL}/${url}`,
     body: data,
     json: config.headers['Content-Type'] === 'application/json',
     agent
   };

  
  return new Promise((resolve, reject) => {
    request(options, function callback(error, response, body) {
      if (error) {
        reject(error);
      } else if (response.statusCode !== 200) {
        if (response.statusCode === 401) {
          reject(response && response.body ? response.body : `Received response from BrowserStack Server with status : ${response.statusCode}`);
        } else {
          reject(`Received response from BrowserStack Server with status : ${response.statusCode}`);
        }
      } else {
        try {
          if (body && typeof(body) !== 'object') {body = JSON.parse(body)}
        } catch (e) {
          reject('Not a JSON response from BrowserStack Server');
        }
        resolve({
          data: body
        });
      }
    });
  });
};
```

2023-05-25 09:24 UTC, merged